{
    "props":[
        "data-name",
        "label",
        "fnLabel",
        "min",
        "max",
        "step",
        "start",
        "overlay",
        "buttons",
        "onchange",
        "onclick"
    ]
}